language: node_js

sudo: required

matrix:
  include:
  - name: "tests"
    node_js: "13"
    env:
      - TESTSPECS='src/**/*.spec.ts'
      - CHAIN_ENDPOINT='ws://localhost:7545'
    script:
      - npm run testunitcoverage

services:
  - docker

cache:
  npm: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5

notifications:
  webhooks: https://coveralls.io/webhook

before_install:
  - git clone https://github.com/evannetwork/testcore-config.git && cd testcore-config
  - docker run -d -p 8546:8546 -p 8545:8545 -v /home/travis/build/evannetwork/dbcp/testcore-config/testcore.json:/root/parity/spec.json -u root evannetwork/testcore-snapshot --chain /root/parity/spec.json --jsonrpc-interface all --unsafe-expose
  - export CC="gcc-5" && export CXX="g++-5" && export LINK="gcc-5" && export LINKXX="g++-5"
  - npm install -g npm@latest
  - npm i -g ganache-cli
install:
  - cd /home/travis/build/evannetwork/dbcp
  - npm install
  - npm install codecov -g
  - ganache-cli --allowUnlimitedContractSize --gasLimit 0xE4E1C0 -p 7545 -f http://localhost:8545 > /dev/null &
  - cd /home/travis/build/evannetwork/dbcp
after_success:
  - codecov
